name: Run Playwright Tests

on:
  push:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install      

    - name: Run tests
      env:
        TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      run: npm test